#!/usr/bin/env sh

set -eo pipefail

SECRET_KVP="$1"
SECRET_NAME=$(echo $SECRET_KVP | cut -d'=' -f1)
SECRET_ALIAS=$(echo $SECRET_KVP | cut -d'=' -f2)
SECRET_ALIAS=${SECRET_ALIAS:-$SECRET_NAME}
shift

if [[ "$SECRET_NAME" == '' ]]; then
	echo "usage: $0 <secret[=alias]> [key1[=alias1]] [key2[=alias2]] ... [keyN[=aliasN]]"
	exit 2
fi

if ! test -f "$KUBECONFIG"; then
	echo "$KUBECONFIG: please provide a kubeconfig file"
	exit 2
fi

KUBE_NAMESPACE="${KUBE_NAMESPACE:-$K8S_DEFAULT_NAMESPACE}"
echo "fetching $KUBE_NAMESPACE/secret/$SECRET_NAME..."
SECRET_DATA=$(kubectl -n $KUBE_NAMESPACE get secret/$SECRET_NAME -o json | jq .data)

KEYS="$@"
if [[ "$KEYS" == '' ]]; then
	echo "fetching all keys..."
	KEYS=$(echo $SECRET_DATA | jq -r '. | keys[]')
else
	echo "using keys: $KEYS..."
fi

SECRET_PATH="$SECRETS_MNT/$SECRET_ALIAS"
echo "checking secret mount path..."
mkdir -p $SECRET_PATH

for KEY in $KEYS; do
	KEY_NAME=$(echo $KEY | cut -d'=' -f1)
	KEY_ALIAS=$(echo $KEY | cut -d'=' -f2)
	KEY_ALIAS=${KEY_ALIAS:-$KEY_NAME}
    VALUE_DATA=$(echo $SECRET_DATA | jq -r ".[\"$KEY_NAME\"]")
    if [[ "$VALUE_DATA" == "" ]]; then
    	echo "$KEY: key not found in secret"
    	exit 1
    fi
	VALUE_PATH="$SECRET_PATH/$KEY_ALIAS"
    echo "mounting $VALUE_PATH..."
    echo $VALUE_DATA | base64 -d >| $VALUE_PATH
done

echo "done: $(ls $SECRET_PATH | echo $(wc -l)) secret(s) mounted!"
